package:
  name: mwarp1d
  version: 0.2.2


source:
  path: ../


build:
  script: python setup.py install
  number: 3


requirements:
  build:
    - python >=3.7
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - nose
    - future
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib
    - future

# test:
#   imports:
#    - mwarp1d

about:
  summary: A package for manually warping and nonlinearly registering one-dimensional data
  home: https://github.com/0todd0000/mwarp1d
  license: MIT